---
- name: using multiple conditions
  hosts: all
  tasks:
    - name: install package
      package: 
        name: httpd
        state: installed
      when: 
        - ansible_distribution == 'CentOS'
        - ansible_memfree_mb > 100

