---
- name: when demo
  hosts: all
  tasks:
    - name: install vsftpd is enough space in /boot
      package:
        name: vsftpd
        state: latest
      with_items: "{{ ansible_mounts }}"
      when: item.mount == "/boot" and item.size_available > 100000000
